import { expect, test, _electron as electron } from "@playwright/test"; import { createRequire } from "node:module"; import fs from "node:fs"; import os from "node:os"; import path from "node:path";
import { AssertionRepository } from "../../src/domain/graph/assertionRepository"; import { ChangeSetRepository } from "../../src/domain/changeSet/changeSetRepository"; import { PlaythroughRepository } from "../../src/domain/play/playthroughRepository"; import { StoryProfileRepository } from "../../src/domain/story/storyProfileRepository"; import { DocumentRepository } from "../../src/domain/workspace/documentRepository"; import { ResourceRepository } from "../../src/domain/workspace/resourceRepository"; import { openWorkspace } from "../../src/domain/workspace/workspaceRepository"; import type { DesktopApi } from "../../src/shared/ipcContract";
const require = createRequire(import.meta.url); const electronPath = require("electron") as string; const apiKey = process.env.NOVAX_REAL_E2E_API_KEY?.trim() ?? ""; test.skip(!apiKey, "NOVAX_REAL_E2E_API_KEY is required for real Player evidence.");

test("runs a visible real GM Writer Checker turn and persists immutable audit", async () => {
  test.setTimeout(300_000); const root = fs.mkdtempSync(path.join(os.tmpdir(), "novax-real-player-")); const userData = path.join(root, "user-data"); const workspaceRoot = path.join(root, "workspace"); fs.mkdirSync(workspaceRoot, { recursive: true }); const playthroughId = seed(workspaceRoot);
  const app = await electron.launch({ executablePath: electronPath, args: ["."], env: { ...process.env, NOVAX_DESKTOP_E2E_USER_DATA: userData, NOVAX_DESKTOP_E2E_WORKSPACE: workspaceRoot } });
  try { const page = await app.firstWindow(); await page.setViewportSize({ width: 1440, height: 900 }); await page.evaluate(async (key) => { const api = (globalThis as typeof globalThis & { novaxDesktop: DesktopApi }).novaxDesktop; await api.provider.save({ config: { providerId: "deepseek", displayName: "DeepSeek", baseUrl: "https://api.deepseek.com", modelId: "deepseek-chat", contextWindow: 128000, maxTokens: 2048, reasoning: false, input: ["text"] }, apiKey: key }); }, apiKey);
    await page.getByRole("radio", { name: "玩家模式" }).click(); await page.getByLabel("故事配置").selectOption({ label: "银湾游玩" }); await page.getByRole("button", { name: /存档 1/ }).click(); await page.getByLabel("玩家行动").fill("现在正值退潮，我沿着已知安全石阶进入银湾洞穴的入口第一平台，并停在那里。"); await page.getByTitle("提交行动").click();
    await expect(page.locator(".player-turn-card")).toHaveCount(1);
    const terminal = await Promise.race([
      expect(page.locator(".player-turn-card")).toHaveCount(2, { timeout: 240_000 }).then(() => ({ type: "card" as const, message: "" })),
      page.getByRole("alert").waitFor({ state: "visible", timeout: 240_000 }).then(async () => ({ type: "error" as const, message: await page.getByRole("alert").innerText() })),
    ]);
    if (terminal.type === "error") throw new Error(`Visible Player run failed: ${terminal.message}; audit=${JSON.stringify(readAudit(workspaceRoot))}`);
    await expect(page.locator(".player-turn-card").last()).toContainText("你选择"); await expect(page.getByRole("main")).not.toContainText(/resolutionId|stateDelta|evidenceIds|gmResolution/);
    const evidence = openWorkspace(workspaceRoot); try { expect(evidence.db.prepare("SELECT COUNT(*) AS count FROM play_turns WHERE playthrough_id = ?").get(playthroughId)).toEqual({ count: 2 }); expect(evidence.db.prepare("SELECT event_type FROM player_agent_audit_events WHERE entity_type = 'run' ORDER BY sequence DESC LIMIT 1").get()).toEqual({ event_type: "completed" }); expect(evidence.db.prepare("SELECT role, COUNT(*) AS count FROM player_agent_invocations GROUP BY role ORDER BY role").all()).toEqual([{ role: "checker", count: 1 }, { role: "gm", count: 1 }, { role: "writer", count: 1 }]); expect(evidence.db.prepare("SELECT COUNT(*) AS count FROM player_agent_audit_events WHERE entity_type = 'invocation' AND actual_provider_id IS NOT NULL AND context_policy_version IS NOT NULL").get()).toEqual({ count: 3 }); } finally { evidence.close(); }
  } finally { await app.close(); fs.rmSync(root, { recursive: true, force: true }); }
});

function seed(root: string) { const w = openWorkspace(root); try { const resources = new ResourceRepository(w), documents = new DocumentRepository(w), assertions = new AssertionRepository(w), changes = new ChangeSetRepository(w); const change = changes.propose({ idempotencyKey: "real-player-base", mode: "assist", summary: "建立玩家正史" }); let worldId = "", storyId = ""; const commitId = changes.commit(change.id, "建立玩家正史", (checkpointId) => { const roots = resources.listCurrent(); worldId = resources.putRevision({ checkpointId, type: "world", objectKind: "world", title: "银湾世界", parentId: roots.find((item) => item.type === "world")!.id, state: "active" }); storyId = resources.putRevision({ checkpointId, type: "story", objectKind: "story", title: "潮痕", parentId: roots.find((item) => item.type === "story")!.id, state: "active" }); const versionId = documents.putVersion({ resourceId: worldId, checkpointId, content: "银湾洞穴只在退潮时开放。退潮时，入口石阶通往洞穴入口第一平台，石阶结构稳定，可以安全步行。涨潮时入口被海水完全封死。第一平台之后的区域没有可靠记录。", authorKind: "user" }); assertions.putVersion({ assertionId: "silver-cave-rule", checkpointId, scopeType: "world", scopeId: worldId, subject: "银湾洞穴入口", predicate: "通行条件", object: { tide: "low", destination: "入口第一平台", path: "稳定石阶", traversable: true }, status: "current", source: { kind: "document_version", ref: versionId } }); }); const profile = new StoryProfileRepository(w).create({ storyResourceId: storyId, worldResourceId: worldId, canonCommitId: commitId, title: "银湾游玩" }); const plays = new PlaythroughRepository(w); const play = plays.create({ storyProfileId: profile.id }); plays.appendTurn({ playthroughId: play.id, playerAction: "抵达银湾海岸", gmResolution: { status: "resolved", resolutionId: "setup", evidenceIds: [], outcome: "抵达海岸", consequences: [], stateDelta: { location: "银湾海岸", tide: "low" }, narrativeFacts: ["当前正值退潮"] }, writerText: "你抵达银湾海岸，潮水已经退去。", stateSnapshot: { location: "银湾海岸", tide: "low" } }); return play.id; } finally { w.close(); } }
function readAudit(root: string) { const w = openWorkspace(root); try { return { runs: w.db.prepare("SELECT id FROM player_agent_runs").all().length, invocations: w.db.prepare("SELECT role FROM player_agent_invocations ORDER BY created_at").all(), terminals: w.db.prepare("SELECT entity_type, event_type, error_code FROM player_agent_audit_events ORDER BY sequence").all() }; } finally { w.close(); } }
