#[cfg(test)]
extern crate self as novelx_runtime;

pub mod agent_loop_journal;
pub mod agent_loop_service;
pub mod artifact_store;
pub mod context_compile_service;
pub mod context_compiler;
pub mod continuation_context_service;
pub mod event_journal;
pub mod goal_aggregate;
pub mod live_agent_loop_runner;
pub mod plan_aggregate;
pub mod project_file_tools;
pub mod project_path;
pub mod project_search_tools;
pub mod project_tool_dispatcher;
pub mod project_tool_execution_service;
pub mod provider_attempt;
pub mod provider_gateway;
pub mod provider_inference_protocol;
pub mod provider_inference_service;
pub mod provider_tool_materializer;
pub mod recovery;
pub mod run_aggregate;
pub mod run_command_service;
pub mod run_reconciliation_service;
pub mod run_state;
pub mod runtime_actor;
pub mod tool_aggregate;
pub mod tool_coordination_service;
pub mod tool_protocol_mapper;
pub mod tool_state;
pub mod workspace_event_journal;
